repos:
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Run black
        entry: bash -c "black ."
        language_version: python3.7
        types: [python]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        name: Run flake8
        entry: bash -c "flake8"
        language_version: python3.7

default_language_version:
  python: python3.7
