version: '3'

services:
  redpanda:
    image: vectorized/redpanda:v22.1.4-amd64
    command:
      - redpanda
      - start
      - "--smp"
      - "4"
      - "--reserve-memory"
      - 0M
      - "--memory"
      - 4G
      - "--overprovisioned"
      - "--node-id"
      - "0"
      - "--check=false"
      - "--kafka-addr"
      - "PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092"
      - "--advertise-kafka-addr"
      - "PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092"
    ports:
      - "9092:9092"
      - "9644:9644"

  stream:
    image: ghcr.io/singularity-data/risingwave:v0.1.10
    command: playground
    ports:
    - 5691:5691
    - 4566:4566
