[tool.poetry]
name = "twitter-mining"
version = "0.1.0"
description = ""
authors = ["Muhammad Daffa Dinaya <13518141@std.stei.itb.ac.id>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
aiodns = "3.0.0"
aiohttp = "3.8.1"
aiohttp-socks = "0.7.1"
aiosignal = "1.2.0"
async-timeout = "4.0.2"
asynctest = "0.13.0"
attrs = "21.2.0"
"backports.entry-points-selectable" = "1.1.1"
beautifulsoup4 = "4.10.0"
CacheControl = "0.12.10"
cachy = "0.3.0"
cchardet = "2.1.7"
certifi = "2021.10.8"
cffi = "1.15.0"
charset-normalizer = "2.0.9"
cleo = "0.8.1"
clikit = "0.6.2"
crashtest = "0.3.1"
cryptography = "36.0.1"
dataclasses = "0.6"
distlib = "0.3.4"
elasticsearch = "7.16.1"
fake-useragent = "0.1.11"
filelock = "3.4.0"
frozenlist = "1.2.0"
geographiclib = "1.52"
geopy = "2.2.0"
googletransx = "2.4.2"
html5lib = "1.1"
idna = "3.3"
importlib-metadata = "1.7.0"
jeepney = "0.7.1"
keyring = "21.8.0"
lockfile = "0.12.2"
msgpack = "1.0.3"
multidict = "5.2.0"
numpy = "1.21.5"
packaging = "20.9"
pandas = "1.3.5"
pastel = "0.2.1"
pexpect = "4.8.0"
pkginfo = "1.8.2"
platformdirs = "2.4.0"
poetry = "1.1.12"
poetry-core = "1.0.7"
ptyprocess = "0.7.0"
pycares = "4.1.2"
pycparser = "2.21"
pylev = "1.4.0"
pyparsing = "3.0.6"
PySocks = "1.7.1"
python-dateutil = "2.8.2"
python-socks = "2.0.1"
pytz = "2021.3"
requests = "2.26.0"
requests-toolbelt = "0.9.1"
schedule = "1.1.0"
SecretStorage = "3.3.1"
shellingham = "1.4.0"
six = "1.16.0"
soupsieve = "2.3.1"
tomlkit = "0.8.0"
twint = {git = "https://github.com/mdaffad/twint.git", rev = "fix-language"}
typing-extensions = "4.0.1"
urllib3 = "1.26.7"
virtualenv = "20.10.0"
webencodings = "0.5.1"
yarl = "1.7.2"
zipp = "3.6.0"
pre-commit = "^2.16.0"

[tool.poetry.dev-dependencies]
black = "^21.12b0"
isort = "^5.10.1"
flake8 = "^4.0.1"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 79

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
