[tool.poetry]
name = "springhead"
version = "0.0.1"
description = "Clustering Framework for Apache Flink"
authors = ["Muhammad Daffa Dinaya <13518141@std.stei.itb.ac.id>"]
license = "The MIT License"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
twint = {path = "packages/twint-0.1.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
