from .requests import SpringheadTimeCreateRequest
from .text import (
    SPRINGHEAD_CLUSTREAM_VALUE_SPEC,
    SPRINGHEAD_DFS_VALUE_SPEC,
    SPRINGHEAD_N_DOCUMENT_VALUE_SPEC,
    SPRINGHEAD_STRING_TYPE,
    SPRINGHEAD_TEXT_EGRESS_RECORD_TYPE,
    SpringheadType,
)
